language: java
sudo: true

matrix:
  fast_finish: true
  include:
    - jdk: openjdk7
      env: TASKS="check"
    - jdk: oraclejdk7
      env: TASKS="check"
    - jdk: oraclejdk8
      env: TASKS="cobertura coveralls"

script:
  - ./gradlew clean $TASKS --no-daemon --stacktrace

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/

addons:
  hosts:
    - phabplugintesthost
  hostname: phabplugintesthost
