---
language: java

matrix:
  fast_finish: true
  include:
    - jdk: openjdk7
      env: MAIN_ARGS="test"
    - jdk: oraclejdk7
      env: MAIN_ARGS="cobertura:cobertura coveralls:report"

script:
  - mvn clean $MAIN_ARGS
